const express = require('express'); //Строка 1
const app = express(); //Строка 2
const port = process.env.PORT || 5000; //Строка 3

// Сообщение о том, что сервер запущен и прослушивает указанный порт
app.listen(port, () => console.log(`Listening on port ${port}`)); //Строка 6

// Создание GET маршрута
app.get('/express_backend', (req, res) => {
  //Строка 9
  const responseData = {
    data: [
      {
        id: '1',
        title: 'Люстра VODA',
        description:
          'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.',
        'discount-price': '45000',
        price: 60000,
        likes: 65,
        room: 'гостиная',
        category: 'свет',
        'in-sale': 'true',
        rating: '5',
        src: './IMG/voda.png',
      },
      {
        id: '2',
        title: 'Кресло VILORA',
        description:
          'Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань.',
        'discount-price': '21000',
        price: 35000,
        likes: 75,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.5',
        src: './IMG/catalog5.jpg',
      },
      {
        id: '4',
        title: 'Стол MENU',
        description:
          'Для того чтобы трапезничать было приятно, необходим правильный обеденный стол.',
        'discount-price': '20000',
        price: 34000,
        likes: 85,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'true',
        rating: '3',
        src: './IMG/table.png',
      },
      {
        id: '5',
        title: 'Диван ASKESTA',
        description:
          'Благодаря защелкивающемуся механизму диван легко раскладывается в комфортную кровать',
        'discount-price': '68000',
        price: 65000,
        likes: 995,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '4.7',
        src: './IMG/askesta.png',
      },
      {
        id: '6',
        title: 'Кресло LUNAR',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 45000,
        likes: 25,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.6',
        src: './IMG/lunar.png',
      },
      {
        id: '7',
        title: 'Шкаф Nastan',
        description:
          'Мебель может быть оснащена разнообразными системами подсветки.',
        'discount-price': '80000',
        price: 85000,
        likes: 15,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'false',
        rating: '4.1',
        src: './IMG/catalog6.jpg',
      },
      {
        id: '8',
        title: 'Комод VENT',
        description:
          'Европейский дуб - отличается особой прочностью и стабильностью.',
        'discount-price': 43000,
        price: 46000,
        likes: 235,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'true',
        rating: '4.3',
        src: './IMG/vent.png',
      },
      {
        id: '9',
        title: 'Диван RONALD',
        description:
          'Модель отличается простотой линий и форм, отсутствием броского декора.',
        'discount-price': 156000,
        price: 166000,
        likes: 445,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '5',
        src: './IMG/ronald.png',
      },
      {
        id: '10',
        title: 'Стол NORMAN',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 46000,
        likes: 655,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'false',
        rating: '4',
        src: './IMG/catalog3.jpg',
      },
      {
        id: '11',
        title: 'Люстра VODA',
        description:
          'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.',
        'discount-price': '45000',
        price: 60000,
        likes: 65,
        room: 'гостиная',
        category: 'свет',
        'in-sale': 'true',
        rating: '5',
        src: './IMG/voda.png',
      },
      {
        id: '12',
        title: 'Кресло VILORA',
        description:
          'Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань.',
        'discount-price': '21000',
        price: 35000,
        likes: 75,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.5',
        src: './IMG/catalog5.jpg',
      },
      {
        id: '13',
        title: 'Стол MENU',
        description:
          'Для того чтобы трапезничать было приятно, необходим правильный обеденный стол.',
        'discount-price': '20000',
        price: 34000,
        likes: 85,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'true',
        rating: '3',
        src: './IMG/table.png',
      },
      {
        id: '14',
        title: 'Диван ASKESTA',
        description:
          'Благодаря защелкивающемуся механизму диван легко раскладывается в комфортную кровать',
        'discount-price': '68000',
        price: 65000,
        likes: 995,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '4.7',
        src: './IMG/askesta.png',
      },
      {
        id: '15',
        title: 'Кресло LUNAR',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 45000,
        likes: 25,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.6',
        src: './IMG/lunar.png',
      },
      {
        id: '16',
        title: 'Шкаф Nastan',
        description:
          'Мебель может быть оснащена разнообразными системами подсветки.',
        'discount-price': '80000',
        price: 85000,
        likes: 15,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'false',
        rating: '4.1',
        src: './IMG/catalog6.jpg',
      },
      {
        id: '17',
        title: 'Комод VENT',
        description:
          'Европейский дуб - отличается особой прочностью и стабильностью.',
        'discount-price': 43000,
        price: 46000,
        likes: 235,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'true',
        rating: '4.3',
        src: './IMG/vent.png',
      },
      {
        id: '18',
        title: 'Диван RONALD',
        description:
          'Модель отличается простотой линий и форм, отсутствием броского декора.',
        'discount-price': 156000,
        price: 166000,
        likes: 445,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '5',
        src: './IMG/ronald.png',
      },
      {
        id: '19',
        title: 'Стол NORMAN',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 46000,
        likes: 655,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'false',
        rating: '4',
        src: './IMG/catalog3.jpg',
      },
      {
        id: '20',
        title: 'Люстра VODA',
        description:
          'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.',
        'discount-price': '45000',
        price: 60000,
        likes: 65,
        room: 'гостиная',
        category: 'свет',
        'in-sale': 'true',
        rating: '5',
        src: './IMG/voda.png',
      },
      {
        id: '21',
        title: 'Кресло VILORA',
        description:
          'Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань.',
        'discount-price': '21000',
        price: 35000,
        likes: 75,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.5',
        src: './IMG/catalog5.jpg',
      },
      {
        id: '22',
        title: 'Стол MENU',
        description:
          'Для того чтобы трапезничать было приятно, необходим правильный обеденный стол.',
        'discount-price': '20000',
        price: 34000,
        likes: 85,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'true',
        rating: '3',
        src: './IMG/table.png',
      },
      {
        id: '23',
        title: 'Диван ASKESTA',
        description:
          'Благодаря защелкивающемуся механизму диван легко раскладывается в комфортную кровать',
        'discount-price': '68000',
        price: 65000,
        likes: 995,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '4.7',
        src: './IMG/askesta.png',
      },
      {
        id: '24',
        title: 'Кресло LUNAR',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 45000,
        likes: 25,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.6',
        src: './IMG/lunar.png',
      },
      {
        id: '25',
        title: 'Шкаф Nastan',
        description:
          'Мебель может быть оснащена разнообразными системами подсветки.',
        'discount-price': '80000',
        price: 85000,
        likes: 15,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'false',
        rating: '4.1',
        src: './IMG/catalog6.jpg',
      },
      {
        id: '26',
        title: 'Комод VENT',
        description:
          'Европейский дуб - отличается особой прочностью и стабильностью.',
        'discount-price': 43000,
        price: 46000,
        likes: 235,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'true',
        rating: '4.3',
        src: './IMG/vent.png',
      },
      {
        id: '27',
        title: 'Диван RONALD',
        description:
          'Модель отличается простотой линий и форм, отсутствием броского декора.',
        'discount-price': 156000,
        price: 166000,
        likes: 445,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '5',
        src: './IMG/ronald.png',
      },
      {
        id: '28',
        title: 'Стол NORMAN',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 46000,
        likes: 655,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'false',
        rating: '4',
        src: './IMG/catalog3.jpg',
      },
      {
        id: '29',
        title: 'Люстра VODA',
        description:
          'Основание из полированной нержавеющей стали, придает оригинальный парящий эффект.',
        'discount-price': '45000',
        price: 60000,
        likes: 65,
        room: 'гостиная',
        category: 'свет',
        'in-sale': 'true',
        rating: '5',
        src: './IMG/voda.png',
      },
      {
        id: '30',
        title: 'Кресло VILORA',
        description:
          'Мягкое и уютное, аккуратное и стильное. Упругие подушки сиденья и приятная на ощупь ткань.',
        'discount-price': '21000',
        price: 35000,
        likes: 75,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.5',
        src: './IMG/catalog5.jpg',
      },
      {
        id: '31',
        title: 'Стол MENU',
        description:
          'Для того чтобы трапезничать было приятно, необходим правильный обеденный стол.',
        'discount-price': '20000',
        price: 34000,
        likes: 85,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'true',
        rating: '3',
        src: './IMG/table.png',
      },
      {
        id: '32',
        title: 'Диван ASKESTA',
        description:
          'Благодаря защелкивающемуся механизму диван легко раскладывается в комфортную кровать',
        'discount-price': '68000',
        price: 65000,
        likes: 995,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '4.7',
        src: './IMG/askesta.png',
      },
      {
        id: '33',
        title: 'Кресло LUNAR',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 45000,
        likes: 25,
        room: 'гостиная',
        category: 'кресло',
        'in-sale': 'true',
        rating: '4.6',
        src: './IMG/lunar.png',
      },
      {
        id: '34',
        title: 'Шкаф Nastan',
        description:
          'Мебель может быть оснащена разнообразными системами подсветки.',
        'discount-price': '80000',
        price: 85000,
        likes: 15,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'false',
        rating: '4.1',
        src: './IMG/catalog6.jpg',
      },
      {
        id: '35',
        title: 'Комод VENT',
        description:
          'Европейский дуб - отличается особой прочностью и стабильностью.',
        'discount-price': 43000,
        price: 46000,
        likes: 235,
        room: 'спальня',
        category: 'хранение',
        'in-sale': 'true',
        rating: '4.3',
        src: './IMG/vent.png',
      },
      {
        id: '36',
        title: 'Диван RONALD',
        description:
          'Модель отличается простотой линий и форм, отсутствием броского декора.',
        'discount-price': 156000,
        price: 166000,
        likes: 445,
        room: 'гостиная',
        category: 'диван',
        'in-sale': 'false',
        rating: '5',
        src: './IMG/ronald.png',
      },
      {
        id: '37',
        title: 'Стол NORMAN',
        description:
          'Прекрасно переносит солнечные лучи, перепады влажности и любые осадки',
        'discount-price': '40000',
        price: 46000,
        likes: 655,
        room: 'кухня',
        category: 'стол',
        'in-sale': 'false',
        rating: '4',
        src: './IMG/catalog3.jpg',
      },
    ],
  };
  res.json(responseData);
}); //Строка 11
